version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - mvn -B clean package
      - mkdir -p bundle
      - cp target/*.jar bundle/app.jar
      - printf "web: java -jar app.jar\n" > bundle/Procfile
      - cd bundle
      - zip -r ../app-bundle.zip .
      - cd ..

artifacts:
  files:
    - app-bundle.zip